Importing Thumbnails via JWPlatform API
uisautomation/sms2jwplayer pull request #19
Opened 2018-05-03 10:37 UTC by msb

closes: #17

2018-05-03 12:12 UTC, rjw57 requested changes
Minor changes. The overall approach looks fine.

2018-05-03 12:12 UTC, rjw57 commented on scripts/export_sms_csv.sh
> +        md5(i.data) AS image_md5,
Can we use consistent indenting? (Does this mean the .editorconfig needs updating?)

2018-05-03 12:12 UTC, rjw57 commented on scripts/export_sms_csv.sh
> +		JOIN sms_clip ON sms_clip.media_id = m.id
Why do these need reversing?

2018-05-03 12:12 UTC, rjw57 commented on sms2jwplayer/csv.py
> +* ``image_id`` - The id of the media item's thumbnail - empty if a thumbnail was never uploaded.
Can we clarify "never uploaded"? Uploaded to SMS or JWPlatform? I'd thought the latter when I read this comment but reviewing the later code makes me think the former. Perhaps replace with "if no custom thumbnail was uploaded to the legacy SMS, this is None"?

2018-05-03 12:12 UTC, rjw57 commented on sms2jwplayer/genupdatejob.py
>              # Key is not in source, set it in delta
Good catch. :S

2018-05-03 12:12 UTC, rjw57 commented on requirements.txt
> +git+https://github.com/jwplayer/jwplatform-py#egg=jwplatform
Since release 1.2.2 is now out, we no longer need to use the version of jwplatform-py from master. Can we remove this?

2018-05-03 12:12 UTC, rjw57 commented on sms2jwplayer/genupdatejob.py
> +            if item.image_md5 and 'sms_image_md5' in delta.get('custom', {}):
Should this also check that ``sms_image_status`` somehow? E.g. if the update job dies half way and the ``sms_image_md5`` prop is set but the thumbnail was not actually loaded. I'd have expected the next genupdatejob to notice that. Maybe something like:

```python
image_status = get_key_path(video, 'custom.sms_image_status')
video_image_md5, expected_video_image_md5 = [
    get_key_path(v, 'custom.sms_image_md5') for v in (video, expected_video)
]
image_md5_mismatch = video_image_md5 != expected_video_image_md5

# We want to trigger an upload of an image in the following circumstances:
#   - The MD5s do not match *and* there is not an upload currently in progress
md5_mismatch = (
    video_image_md5 != expected_video_image_md5 and
    image_status != 'image_status:loaded:'
)
#   - The MD5s match but the matching upload was never attempted
no_upload = (
    video_image_md5 and
    video_image_md5 == expected_video_image_md5 and
    not image_status
)
if md5_mismatch or no_upload:
   # ...
```

2018-05-03 12:12 UTC, rjw57 commented on sms2jwplayer/test/util.py
> +        return patcher.start()
"neat"

2018-05-03 12:12 UTC, rjw57 commented on sms2jwplayer/util.py
> +    return json.loads(response.text)
Use ``response.json()``?

2018-05-03 12:42 UTC, msb commented on scripts/export_sms_csv.sh
> +		JOIN sms_clip ON sms_clip.media_id = m.id
i tend to always have the joined table field on the LHS - doesn't affect the actual working of the query at all - it's a "thing", if you will :-)

2018-05-03 12:43 UTC, rjw57 commented on scripts/export_sms_csv.sh
> +		JOIN sms_clip ON sms_clip.media_id = m.id
Hokays.

2018-05-10 09:18 UTC, rjw57 approved these changes

2018-05-10 09:19 UTC, rjw57 approved these changes

2018-05-10 09:20 UTC, rjw57 commented
I'm happy with the code modulo Travis build failing

2018-05-10 09:55 UTC, merged